name = "links-rasio-dev"
main = "src/index.ts"
compatibility_date = "2024-12-30"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[d1_databases]]
binding = "DB"
database_name = "links"
database_id = "7ceab28c-3f2b-493f-9609-4f598f6edee7"
