name = "links-rasio-dev"
main = "src/index.ts"
compatibility_date = "2024-12-30"
assets = { directory = "./public" }
routes = [
  { pattern = "links.rasio.dev", custom_domain = true }
]

# [vars]
# MY_VAR = "my-variable"

[[d1_databases]]
binding = "DB"
database_name = "links"
database_id = "640ef3af-2976-4332-97c7-e602c3f8f6d2"
